// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw3jl_NzrCJu3tLocBeh4Ht0rq3RPoqVk',
    appId: '1:80974884525:web:543bdf36ea611c96b2a024',
    messagingSenderId: '80974884525',
    projectId: 'wordle-game-a825b',
    authDomain: 'wordle-game-a825b.firebaseapp.com',
    databaseURL: 'https://wordle-game-a825b-default-rtdb.firebaseio.com',
    storageBucket: 'wordle-game-a825b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmidvLoaPe3DYoEcFopTTMiw6kAcHP7G8',
    appId: '1:80974884525:android:cb4caf3022c496f0b2a024',
    messagingSenderId: '80974884525',
    projectId: 'wordle-game-a825b',
    databaseURL: 'https://wordle-game-a825b-default-rtdb.firebaseio.com',
    storageBucket: 'wordle-game-a825b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsVXGkJxumi7kNdYDQym9-25ppzH98kdI',
    appId: '1:80974884525:ios:6efd25422a9b037ab2a024',
    messagingSenderId: '80974884525',
    projectId: 'wordle-game-a825b',
    databaseURL: 'https://wordle-game-a825b-default-rtdb.firebaseio.com',
    storageBucket: 'wordle-game-a825b.appspot.com',
    iosBundleId: 'com.example.wordle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsVXGkJxumi7kNdYDQym9-25ppzH98kdI',
    appId: '1:80974884525:ios:7be1b42a5183e2dab2a024',
    messagingSenderId: '80974884525',
    projectId: 'wordle-game-a825b',
    databaseURL: 'https://wordle-game-a825b-default-rtdb.firebaseio.com',
    storageBucket: 'wordle-game-a825b.appspot.com',
    iosBundleId: 'com.example.wordle.RunnerTests',
  );
}
